apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ghapps-nodejsapp"
  description: An example template
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  
